blank_issues_enabled: false
contact_links:
  - name: Discussion
    url: https://github.com/kawacukennedy/community_voice_ews/discussions
    about: Ask questions and discuss ideas here
  - name: Security
    url: https://github.com/kawacukennedy/community_voice_ews/security/policy
    about: Report security vulnerabilities here
